version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "15000:22"
      - "15001:3000"
      - "15002:8000"
    volumes:
      - "./home:/home/sparcs"
    environment:
      - NEW_PASSWORD=1234
    depends_on:
      - db

  db:
    image: mysql:8.4.0
    restart: always
    volumes:
      - data:/data/db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db

volumes:
  data: