services:
  ||USER||-app:
    container_name: ||USER||-app
    image: ghcr.io/sparcs-kaist/newbie-image:latest
    restart: always
    ports:
      - "||PORT22||:22"
      - "||PORT3000||:3000"
      - "||PORT8000||:8000"
    volumes:
      - "./||USER||/home:/home/sparcs"
    environment:
      - NEW_PASSWORD=||NEW_PASSWORD||
    depends_on:
      - db
    networks:
      - default
      - proxy

  ||USER||-db:
    container_name: ||USER||-db
    image: mysql:8.4.0
    restart: always
    volumes:
      - ./||USER||/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=||MYSQL_ROOT_PASSWORD||
      - MYSQL_DATABASE=db
    networks:
      - default

networks:
  ||USER||-network:
  proxy:
    external: true