version: '3'

services:
  app:
    image: ghcr.io/sparcs-kaist/newbie-image:latest
    restart: always
    ports:
      - "15000:22"
      - "15001:3000"
      - "15002:8000"
    volumes:
      - "./home:/home/sparcs"
    environment:
      - NEW_PASSWORD=||NEW_PASSWORD||
    depends_on:
      - db

  db:
    image: mysql:8.4.0
    restart: always
    volumes:
      - data:/data/db
    environment:
      - MYSQL_ROOT_PASSWORD=||MYSQL_ROOT_PASSWORD||
      - MYSQL_DATABASE=db

volumes:
  data: